/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteImport } from './routes/_tabs'
import { Route as TabsIndexRouteImport } from './routes/_tabs/index'
import { Route as TabsAccountRouteImport } from './routes/_tabs/account'
import { Route as TabsCartRouteImport } from './routes/_tabs/cart'
import { Route as TabsOrdersRouteImport } from './routes/_tabs/orders'
import { Route as MenuOfferingIdRouteImport } from './routes/menu/$offeringId'
import { Route as VendorsVendorIdRouteImport } from './routes/vendors/$vendorId'

const TabsRoute = TabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsIndexRoute = TabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TabsRoute,
} as any)
const TabsAccountRoute = TabsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => TabsRoute,
} as any)
const TabsCartRoute = TabsCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => TabsRoute,
} as any)
const TabsOrdersRoute = TabsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => TabsRoute,
} as any)
const MenuOfferingIdRoute = MenuOfferingIdRouteImport.update({
  id: '/menu/$offeringId',
  path: '/menu/$offeringId',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsVendorIdRoute = VendorsVendorIdRouteImport.update({
  id: '/vendors/$vendorId',
  path: '/vendors/$vendorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof TabsIndexRoute
  '/account': typeof TabsAccountRoute
  '/cart': typeof TabsCartRoute
  '/orders': typeof TabsOrdersRoute
  '/menu/$offeringId': typeof MenuOfferingIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
}
export interface FileRoutesByTo {
  '/account': typeof TabsAccountRoute
  '/cart': typeof TabsCartRoute
  '/orders': typeof TabsOrdersRoute
  '/menu/$offeringId': typeof MenuOfferingIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/': typeof TabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_tabs': typeof TabsRouteWithChildren
  '/_tabs/account': typeof TabsAccountRoute
  '/_tabs/cart': typeof TabsCartRoute
  '/_tabs/orders': typeof TabsOrdersRoute
  '/menu/$offeringId': typeof MenuOfferingIdRoute
  '/vendors/$vendorId': typeof VendorsVendorIdRoute
  '/_tabs/': typeof TabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/orders'
    | '/menu/$offeringId'
    | '/vendors/$vendorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/cart'
    | '/orders'
    | '/menu/$offeringId'
    | '/vendors/$vendorId'
    | '/'
  id:
    | '__root__'
    | '/_tabs'
    | '/_tabs/account'
    | '/_tabs/cart'
    | '/_tabs/orders'
    | '/menu/$offeringId'
    | '/vendors/$vendorId'
    | '/_tabs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TabsRoute: typeof TabsRouteWithChildren
  MenuOfferingIdRoute: typeof MenuOfferingIdRoute
  VendorsVendorIdRoute: typeof VendorsVendorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/': {
      id: '/_tabs/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TabsIndexRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/account': {
      id: '/_tabs/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof TabsAccountRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/cart': {
      id: '/_tabs/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof TabsCartRouteImport
      parentRoute: typeof TabsRoute
    }
    '/_tabs/orders': {
      id: '/_tabs/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof TabsOrdersRouteImport
      parentRoute: typeof TabsRoute
    }
    '/menu/$offeringId': {
      id: '/menu/$offeringId'
      path: '/menu/$offeringId'
      fullPath: '/menu/$offeringId'
      preLoaderRoute: typeof MenuOfferingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$vendorId': {
      id: '/vendors/$vendorId'
      path: '/vendors/$vendorId'
      fullPath: '/vendors/$vendorId'
      preLoaderRoute: typeof VendorsVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TabsRouteChildren {
  TabsAccountRoute: typeof TabsAccountRoute
  TabsCartRoute: typeof TabsCartRoute
  TabsOrdersRoute: typeof TabsOrdersRoute
  TabsIndexRoute: typeof TabsIndexRoute
}

const TabsRouteChildren: TabsRouteChildren = {
  TabsAccountRoute: TabsAccountRoute,
  TabsCartRoute: TabsCartRoute,
  TabsOrdersRoute: TabsOrdersRoute,
  TabsIndexRoute: TabsIndexRoute,
}

const TabsRouteWithChildren = TabsRoute._addFileChildren(TabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  TabsRoute: TabsRouteWithChildren,
  MenuOfferingIdRoute: MenuOfferingIdRoute,
  VendorsVendorIdRoute: VendorsVendorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
